USE SPRINT2;

CREATE TABLE AREA (
  ID_AREA INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE FUNCIONARIO (
  ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
  FK_SUPERVISOR INT,
  FK_AREA INT NOT NULL,
  NOME VARCHAR(45) NOT NULL,
  FOREIGN KEY (FK_SUPERVISOR) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
  FOREIGN KEY (FK_AREA) REFERENCES AREA(ID_AREA)
);

INSERT INTO AREA VALUES
	(DEFAULT, 'Marketing', 'Área de marketing da empresa'),
	(DEFAULT, 'Desenvolvimento', 'Área de desenvolvimento de software da empresa'),
	(DEFAULT, 'Financeiro', 'Área financeira da empresa');

INSERT INTO FUNCIONARIO VALUES 
	(DEFAULT, null, 2, 'Matheus Strilicherk'),
	(DEFAULT, 1, 2, 'Carlos Eduardo'),
	(DEFAULT, null, 3, 'Roberto Carvalho'),
	(DEFAULT, 3, 3, 'Diana Leona'),
	(DEFAULT, null, 1, 'Vayne Viktoria'),
	(DEFAULT, 5, 1, 'Giovana Eduarda'),
	(DEFAULT, 1, 2, 'Robson Bobson');
    
SELECT 
    F.NOME
FROM
    FUNCIONARIO F
        JOIN
    FUNCIONARIO AS SUPERVISOR ON FUNCIONARIO.FK_SUPERVISOR = SUPERVISOR.ID_FUNCIONARIO;