CREATE DATABASE ALUNOPROJETO;
USE ALUNOPROJETO;

-- Exercício 1

CREATE TABLE PROJETO (
    ID_PROJETO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE ALUNO (
    ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
    FK_REPRESENTANTE INT,
    FK_PROJETO INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    RA CHAR(8) NOT NULL UNIQUE,
    TELEFONE CHAR(11) NOT NULL UNIQUE,
    FOREIGN KEY (FK_REPRESENTANTE)
        REFERENCES ALUNO (ID_ALUNO),
    FOREIGN KEY (FK_PROJETO)
        REFERENCES PROJETO (ID_PROJETO)
);

INSERT INTO PROJETO VALUES 
	(DEFAULT, 'WHIS{KEY}', 'Controle de temperatura e umidade em destilarias de whisky.'),
	(DEFAULT, 'Stay Cold', 'Controle de temperatura em frigoríficos.'),
	(DEFAULT, 'Bee', 'Controle de temperatura em colmeias de abelha.'),
	(DEFAULT, 'Biblioteca', 'Sistema de biblioteca para a SPTech');
    
INSERT INTO ALUNO VALUES 
	(DEFAULT, NULL, 1, 'Gustavo Henrique', '01252330', '11987653342'),
	(DEFAULT, NULL, 2, 'Rafael Biaggi', '01252335', '11987653245'),
	(DEFAULT, NULL, 3, 'Wagne Moura', '01252213', '11989853342'),
	(DEFAULT, 2, 2, 'Matheus Strilicherk', '01252110', '11999653342'),
	(DEFAULT, 2, 2, 'Gabriel Adryan', '01252120', '11987333342'),
	(DEFAULT, 1, 1, 'Maria Okamoto', '01252333', '11987336501'),
	(DEFAULT, 1, 1, 'Gustavo Kenzo', '01252375', '11987349812');
    
SELECT * FROM ALUNO;
SELECT * FROM PROJETO;

SELECT 
    A.NOME, R.NOME, P.NOME, P.DESCRICAO
FROM
    ALUNO A
        JOIN
    PROJETO P ON A.FK_PROJETO = P.ID_PROJETO
		JOIN
	ALUNO AS R ON A.FK_REPRESENTANTE = R.ID_ALUNO
ORDER BY P.NOME;

SELECT 
    A.NOME, R.NOME
FROM
    ALUNO A
        JOIN
    ALUNO AS R ON A.FK_REPRESENTANTE = R.ID_ALUNO;

SELECT 
    ALUNO.NOME, PROJETO.NOME, DESCRICAO
FROM
    ALUNO
        LEFT JOIN
    PROJETO ON FK_PROJETO = ID_PROJETO
ORDER BY PROJETO.NOME;

-- Exercício 2
CREATE DATABASE CAMPANHA;
USE CAMPANHA;

CREATE TABLE ORGANIZADOR (
    ID_ORGANIZADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FK_ORIENTADOR INT,
    FOREIGN KEY (FK_ORIENTADOR)
        REFERENCES ORGANIZADOR (ID_ORGANIZADOR)
) AUTO_INCREMENT = 30;

CREATE TABLE CAMPANHA (
    ID_CAMPANHA INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,
    INSTITUICAO1 VARCHAR(100) NOT NULL,
    INSTITUICAO2 VARCHAR(100),
    DATA_FINAL DATE NOT NULL,
    FK_ORGANIZADOR INT NOT NULL,
    FOREIGN KEY (FK_ORGANIZADOR)
        REFERENCES ORGANIZADOR (ID_ORGANIZADOR)
) AUTO_INCREMENT = 500;

INSERT INTO ORGANIZADOR VALUES
    (DEFAULT, 'Ana Silva', 'Rua das Flores, 123', 'Centro', 'ana.silva@email.com', NULL),
    (DEFAULT, 'Carlos Pereira', 'Avenida Principal, 456', 'Jardins', 'carlos.pereira@email.com', NULL),
    (DEFAULT, 'Mariana Costa', 'Rua das Pedras, 789', 'Vila Madalena', 'mariana.costa@email.com', 30),
    (DEFAULT, 'João Santos', 'Alameda dos Anjos, 101', 'Pinheiros', 'joao.santos@email.com', 30),
    (DEFAULT, 'Beatriz Lima', 'Travessa da Paz, 202', 'Lapa', 'beatriz.lima@email.com', 31);
    
INSERT INTO CAMPANHA VALUES
    (DEFAULT, 'Alimento', 'Cruz Vermelha', NULL, '2025-10-31', 30),
    (DEFAULT, 'Produto de Higiene', 'Hospital das Clínicas', NULL, '2025-11-15', 30),
    (DEFAULT, 'Máscaras de Proteção', 'Posto de Saúde Central', NULL, '2025-10-20', 31),
    (DEFAULT, 'Alimento', 'Banco de Alimentos Municipal', NULL, '2025-11-30', 32),
    (DEFAULT, 'Roupa de Frio', 'Exército da Salvação', NULL, '2025-10-25', 33);
    
SELECT * FROM ORGANIZADOR;
SELECT * FROM CAMPANHA;

SELECT
    O.*, C.*
FROM
    ORGANIZADOR O
        JOIN
    CAMPANHA C ON O.ID_ORGANIZADOR = C.FK_ORGANIZADOR;

SELECT
    O.*, C.*
FROM
    ORGANIZADOR O
        JOIN
    CAMPANHA C ON O.ID_ORGANIZADOR = C.FK_ORGANIZADOR
WHERE
    O.NOME = 'Ana Silva';
    
SELECT
    N.NOME, O.NOME
FROM
    ORGANIZADOR N
        JOIN
    ORGANIZADOR AS O ON N.FK_ORIENTADOR = O.ID_ORGANIZADOR;

SELECT
    N.NOME, O.NOME
FROM
    ORGANIZADOR N
        JOIN
    ORGANIZADOR AS O ON N.FK_ORIENTADOR = O.ID_ORGANIZADOR
WHERE
    O.NOME = 'Ana Silva';
    
SELECT
    N.NOME, C.CATEGORIA, C.INSTITUICAO1, O.NOME
FROM
    ORGANIZADOR N
        JOIN
    CAMPANHA C ON N.ID_ORGANIZADOR = C.FK_ORGANIZADOR
        JOIN
    ORGANIZADOR AS O ON N.FK_ORIENTADOR = O.ID_ORGANIZADOR;
    
SELECT
    N.NOME, C.CATEGORIA, C.DATA_FINAL, O.NOME
FROM
    ORGANIZADOR N
        JOIN
    CAMPANHA C ON N.ID_ORGANIZADOR = C.FK_ORGANIZADOR
        JOIN
    ORGANIZADOR AS O ON N.FK_ORIENTADOR = O.ID_ORGANIZADOR
WHERE
    N.NOME = 'Mariana Costa';
